### ISSUE TITLE
Getting EnvironmentError: Unable to find libfuse

### ISSUE THREAD

**Issue by jornbeyers** [remakeelectric/mqtt-malaria#22]
I first installed python-mosquitto, then used:
"python setup.py build"

and:
"python setup.py install"

When trying to to publish, I get the following error:

malaria publish -P 2 -n 100 -H localhost -s 10       Traceback (most recent call last):
  File "/usr/bin/malaria", line 5, in <module>
    pkg_resources.run_script('mqtt-malaria==0.1-77-g7ae4c97', 'malaria')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/mqtt_malaria-0.1_77_g7ae4c97-py2.7.egg/EGG-INFO/scripts/malaria", line 30, in <module>
    import beem.main
  File "/usr/lib/python2.7/site-packages/mqtt_malaria-0.1_77_g7ae4c97-py2.7.egg/beem/main.py", line 34, in <module>
    import beem.cmds
  File "/usr/lib/python2.7/site-packages/mqtt_malaria-0.1_77_g7ae4c97-py2.7.egg/beem/cmds/__init__.py", line 2, in <module>
    import beem.cmds.subscribe
  File "/usr/lib/python2.7/site-packages/mqtt_malaria-0.1_77_g7ae4c97-py2.7.egg/beem/cmds/subscribe.py", line 34, in <module>
    import beem.listen
  File "/usr/lib/python2.7/site-packages/mqtt_malaria-0.1_77_g7ae4c97-py2.7.egg/beem/listen.py", line 40, in <module>
    import fuse
  File "build/bdist.linux-x86_64/egg/fuse.py", line 69, in <module>
EnvironmentError: Unable to find libfuse

So what's wrong?

**Comment by ralight** [comment]
See https://github.com/remakeelectric/mqtt-malaria/issues/21
