### ISSUE TITLE
Trouble while executing malaria

### ISSUE THREAD

**Issue by marquies** [remakeelectric/mqtt-malaria#31]
Hello!

I just tried to run malaria against vernemq server on another host, but I get an AssertionError.

Env:
* OS: Ubuntu 16.04
* Python: 2.7.11+ (Also tried python3 but failed with a syntax error)
* mqtt-malaria: Head

```
./malaria publish -t -n 100 -P 4 -H 10.1.2.2
Completed workers: 0/4
Completed workers: 0/4
Completed workers: 1/4
Completed workers: 2/4
Completed workers: 2/4
Completed workers: 2/4
Completed workers: 2/4
Completed workers: 2/4
Completed workers: 3/4
Completed workers: 4/4
Traceback (most recent call last):
  File "./malaria", line 31, in <module>
    beem.main.main()
  File "/home/osboxes/dev/mqtt-malaria/beem/main.py", line 53, in main
    options.handler(options)
  File "/home/osboxes/dev/mqtt-malaria/beem/cmds/publish.py", line 201, in run
    s = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError
```

Maybe I have a bad setup or something else. I can connect to the server via telnet, so this isn't a problem. Could you give me a hint?

**Comment by karlp** [comment]
heh, I actually saw that myself yesterday too, first time.  No idea what causes it, and it never happened again for me.  I think it's something when a process dies unexpectedly?  There's no result object from python multiprocessing, no idea how it happens.

**Comment by kevingo** [comment]
got this error , too.

**Comment by Asoul** [comment]
+1 got this error

**Comment by sky3d** [comment]
I've got the same error when I specify outer host or host by the local computer name during publishing.  Note that `-H localhost` or` -H 127.0.0.1` works ok
Environment:
- MacOS: 10.12.1
- Python 2.7.10
- mqtt-malaria: last

**Comment by sky3d** [comment]
Hi

I've resolve my problem above by temporary modifying malaria scripts and specifying user and password for remote connection like that:

`self.mqttc.username_pw_set(_my_user_, _my_password_)`

Note:  Files to be changed - `mqtt-malaria\beem\listen.py`  and `mqtt-malaria\beem\load.py`

Please review the **"guest" user can only connect via localhost** section at https://www.rabbitmq.com/access-control.html

> By default, the guest user is prohibited from connecting to the broker remotely; it can only connect over a loopback interface (i.e. localhost). This applies both to AMQP and to any other protocols enabled via plugins. Any other users you create will not (by default) be restricted in this way.
> 
> This is configured via the loopback_users item in the configuration file.
> 
> If you wish to allow the guest user to connect from a remote host, you should set the loopback_users configuration item to []. A complete rabbitmq.config which does this would look like:

Thanks

**Comment by chris-K-lee** [comment]
got this error. (Assertion error)

And then..

I got the error as the following
```
Traceback (most recent call last):
  File "./malaria", line 31, in <module>
    beem.main.main()
  File "/Users/chrislee/Daliworks-PC/git/mqtt-malaria/beem/main.py", line 53, in main
    options.handler(options)
  File "/Users/chrislee/Daliworks-PC/git/mqtt-malaria/beem/cmds/publish.py", line 202, in run
    s = result.get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: object of type 'int' has no len()
```

how can I use `mqtt-malaria` again?
please let me know it.

**Comment by Arqu** [comment]
My issue was that my broker doesn't accept any other characters for the client id except letters.
https://github.com/remakeelectric/mqtt-malaria/blob/master/beem/cmds/publish.py#L98
Changed that to account for the situation and now it works for me.
