### ISSUE TITLE
getting socket.gaierror on execution

### ISSUE THREAD

**Issue by aryanurag** [remakeelectric/mqtt-malaria#35]
This error keeps on appearing on any hostname that I try. Also how do you publish on a custom topic on my server, couldn't find the required parameter.

./malaria publish -P 8 -n 10000 -H tcp://127.0.0.1/ -p 1883 -s 100
Completed workers: 0/8
Completed workers: 8/8
Traceback (most recent call last):
  File "./malaria", line 31, in <module>
    beem.main.main()
  File "/home/anuragb/Testing/mqtt-malaria-master/beem/main.py", line 53, in main
    options.handler(options)
  File "/home/anuragb/Testing/mqtt-malaria-master/beem/cmds/publish.py", line 201, in run
    s = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
socket.gaierror: [Errno -2] Name or service not known
anuragb@anuragb-Lenovo-H30-50:~/Testing/mqtt-malaria-master$ ./malaria publish -P 8 -n 10000 -H tcp://127.0.0.1 -p 1883 -s 100
Completed workers: 0/8
Completed workers: 7/8
Completed workers: 7/8
Completed workers: 7/8
Completed workers: 7/8
Completed workers: 7/8
Completed workers: 8/8
Traceback (most recent call last):
  File "./malaria", line 31, in <module>
    beem.main.main()
  File "/home/anuragb/Testing/mqtt-malaria-master/beem/main.py", line 53, in main
    options.handler(options)
  File "/home/anuragb/Testing/mqtt-malaria-master/beem/cmds/publish.py", line 201, in run
    s = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
socket.gaierror: [Errno -2] Name or service not known

**Comment by karlp** [comment]
The hostname is an actual hostname, not "tcp://a.b.c.d:1883"

If you want to change topics you'll have to edit the source iirc.
