### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by CodingSpiderFox** [remakeelectric/mqtt-malaria#40]
I dont know how to setup this to run it on my machine.

Which dependencies do I need to install and how. I tried:

`sudo pip3 install paho-mqtt`

```
Collecting paho-mqtt
Installing collected packages: paho-mqtt
Successfully installed paho-mqtt-1.3.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

./malaria

```
Traceback (most recent call last):
  File "./malaria", line 30, in <module>
    import beem.main
  File "/home/user/mqtt-malaria/beem/main.py", line 34, in <module>
    import beem.cmds
  File "/home/user/mqtt-malaria/beem/cmds/__init__.py", line 1, in <module>
    import beem.cmds.publish
  File "/home/user/mqtt-malaria/beem/cmds/publish.py", line 39, in <module>
    import beem.load
  File "/home/user/mqtt-malaria/beem/load.py", line 36, in <module>
    import paho.mqtt.client as mqtt
ImportError: No module named paho.mqtt.client
```

`sudo pip3 install setuptools`

Then I tried to run 
`sudo python3 setup.py install` 

```
/home/user/.local/lib/python3.5/site-packages/setuptools/dist.py:364: UserWarning: The version specified (b'0.1-80-g6a664de') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    "Topic :: System :: Networking"
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 100, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "/usr/lib/python3.5/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 173, in finalize_options
    self.egg_version = self.tagged_version()
  File "/home/user/.local/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 263, in tagged_version
    return safe_version(version + self.vtags)
TypeError: can't concat bytes to str
```

`sudo pip install setuptools && sudo python setup.py install` however worked. It seems that the code is not compatible to python3.

The README should contain the commands to install the required dependencies and mqtt-malaria itself with python 2.7

**Comment by CodingSpiderFox** [comment]
Thanks for the quick resolution

**Comment by joboscribe** [comment]
Perhaps it's my inexperience with Python but i was unable to get this installed.

My steps were
```
pip3 install paho-mqtt
virtualenv .env
. .env/bin/activate
pip install .
```
Which all seemed to work until the last step:
```
(.env)# pip install .
Directory '.' is not installable. File 'setup.py' not found.
```

I have setuptools and fusepy installed via pip3, is there some other requirement i'm missing?

**Comment by karlp** [comment]
drop your step one :)  We jsut updated the readme because of this ticket to explicitly say it was a python2 app.

I don't like the look of your command line with a # in it implying it's a root shell either.  Also, I've no idea what directory you're in.

**Comment by joboscribe** [comment]
Ah, i misread the "or greater" to mean all the previously mentioned items. Never mind.

(I am logged in as root because i'm trying this on a VM.)
